self
part_vals
throw_exception
