{
  try {
    return fn.call();
  }
 catch (  Exception e) {
    throw new HiveException(e);
  }
}
