{
  return this.throw_exception;
}
