{
  boolean foundException=false;
  try {
    testNestedinArrayAtLevel(maxLevel,type,new Properties());
  }
 catch (  SerDeException serdeEx) {
    foundException=true;
  }
  assertTrue("Expected exception for exceeding nesting limit",foundException);
}
